include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    camel_case_types: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore