name: car_rental_locate
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  dio: ^5.0.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  go_router: ^6.0.6
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.0.17
  get_it: ^7.2.0
  nb_utils: ^5.0.5
  intl: ^0.18.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.3
  location: ^4.4.0
  signalr_netcore: ^1.3.3
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
